# Generated by Django 5.0.6 on 2024-06-12 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Ecuaciones',
            fields=[
                ('id_ecuacion', models.AutoField(primary_key=True, serialize=False)),
                ('ecuacion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=50)),
                ('fecha_inicio_sesion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Soluciones',
            fields=[
                ('id_solucion', models.AutoField(primary_key=True, serialize=False)),
                ('text_solucion', models.CharField(max_length=200)),
                ('pasos', models.CharField(max_length=500)),
                ('fecha_solucion', models.DateField()),
                ('id_ecuacion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='calculadora_app.tbl_ecuaciones')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Historial',
            fields=[
                ('id_busqueda', models.AutoField(primary_key=True, serialize=False)),
                ('texto_busqueda', models.DateField(max_length=200)),
                ('fecha_busqueda', models.DateField()),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='calculadora_app.tbl_usuarios')),
            ],
        ),
        migrations.AddField(
            model_name='tbl_ecuaciones',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='calculadora_app.tbl_usuarios'),
        ),
    ]
