# Generated by Django 5.0.6 on 2024-06-13 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_ecuaciones',
            name='fi_ecuacion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tbl_ecuaciones',
            name='xi_ecuacion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_historial',
            name='texto_busqueda',
            field=models.CharField(max_length=200),
        ),
    ]
