# Generated by Django 5.0.6 on 2024-06-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora_app', '0002_tbl_ecuaciones_fi_ecuacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_ecuaciones',
            name='ecuacion_simplificada',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
